version: "3"
services:
  mainservice:
    image: patnaikshekhar/clamavrest:1
    build: .
    ports:
      - 8000:80
    links:
      - clamav
    environment:
      - AZ_ACC_NAME
      - AZ_ACC_KEY
  clamav:
    image: mkodockx/docker-clamav
    